services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  spring:
    image: trissss/influy
    container_name: influy
    env_file: .env
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      RDS_USERNAME: ${RDS_USERNAME}
      RDS_PASSWORD: ${RDS_PASSWORD}
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION: ${S3_REGION}
      S3_ACCESS: ${S3_ACCESS}
      S3_SECRET: ${S3_SECRET}

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/nginx/influy.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - spring

