services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  spring:
    image: trissss/influy
    container_name: influy
    restart: always
    ports:
      - "8080:8081"
    depends_on:
      - redis

