name: CI/CD Pipeline

on:
  push:
    branches: [ "deploy-7" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Create application.yml
        shell: bash
        run: |
          mkdir -p src/main/resources
          cat <<EOF > src/main/resources/application.yml
          ${{ secrets.APPLICATION_PROD_YML }}
          EOF
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew bootJar
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:latest
