name: CI/CD Pipeline

on:
  push:
    branches: [ "deploy-7" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Create application.yml
        run: |
          mkdir -p src/main/resources
          cat <<EOF > src/main/resources/application-prod.yml
          ${{ secrets.APPLICATION_PROD_YML }}
          EOF
          shell: bash
        env:
          DB_password: ${{ secrets.DB_PASSWORD }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build
